### PR TITLE
adds Intel base images

### PR DESCRIPTION
**Pull request by wangyinz**
The new dockerfiles installs Intel Parallel Studio as well as Intel MPI in it. I used TACC's license for the build, but intentionally didn't include the license file in the repo. To build the images, one will need to place a valid license as `containers/extras/intel.lic`. 

I already got the images built and pushed to Docker Hub as [wangyinz/tacc-containers/tacc-centos7-intel19.1.1-impi19.0.7-common](https://hub.docker.com/layers/wangyinz/tacc-containers/tacc-centos7-intel19.1.1-impi19.0.7-common/images/sha256-6949cdcccc72d4539f389ad8edb0282a7c91cb317e70f6c2e4afd86556f33ad3?context=repo) and [wangyinz/tacc-containers/tacc-ubuntu18-intel19.1.1-impi19.0.7-common](https://hub.docker.com/layers/wangyinz/tacc-containers/tacc-ubuntu18-intel19.1.1-impi19.0.7-common/images/sha256-857b1364fc7f4789e06313c7e061bb34ad0310ac5150ddc32181053005119891?context=repo). Should be fine just directly pull and push them into the official Docker Hub repo.

### CODE REVIEW

**Comment by zyndagj** [comment]
I would prefer to hold off on this until we support building containers on TACC systems, so we have a way to recommend their usage.

**Comment by wangyinz** [comment]
The intel compiler image is useful to some of the HPC applications that require a two-step build, where the second step compiles the code with the input data. With this container, the user will be able to directly compile the second step within the container at the beginning of a job and still be able to use intel compiler for better performance.

**Comment by zyndagj** [comment]
Can you document how that would be used on our systems?

**Comment by wangyinz** [comment]
Yes. I can take care of the documentation. The two-step build is quite common for HPC applications, because static memory allocation performs much better than a dynamic one. The application just compiles the problem size into the code at the second stage. This is a known reason why some HPC applications don't have a containerized version. 

With that said, I guess people these days are also transitioning some of those code to dynamic allocations trying to fit the container model. So, the need for such a base container might eventually go away.

Anyway, let me sketch up something on how to use this base container.

**Pull request closed without merging**
